#!/usr/bin/perl -w

if ((scalar @ARGV) != 3) {
	print "Usage: plan <domain> <problem> <solution>\n";
	exit(1);
}

$dom = shift @ARGV;
$prob = shift @ARGV;
$soln = shift @ARGV;

if (!(-e $dom)) {
	print "Domain file $dom not found\n";
	exit(1);
}

if (!(-e $prob)) {
        print "Problem file $prob not found\n";
        exit(1);
}

open IN, "./compile/popf2/popf3-clp -I -n $dom $prob |";

$solnfile = 1;
while (<IN>) {
	if (m/; Plan found/) {
		print "\n\n - Opening plan file $soln.$solnfile\n";
		print;
		open OUT, "> $soln.$solnfile";
		print OUT;
		while (<IN>) {
			if (m/./) {
				print;
				print OUT;
			} else {
				print;
				last;
			}
		}
		close OUT;
		++$solnfile;
	} else {
		print;
	}

}

close IN;
