name: lyrical

on:
  pull_request:
    branches:
      - lyrical-devel
  push:
    branches:
      - lyrical-devel

jobs:
  build-and-test:
    runs-on: ubuntu-26.04
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-resolute-ros-lyrical-ros-base:master
    steps:
      - uses: actions/checkout@v6
        with:
          ref: lyrical-devel
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: popf
          target-ros2-distro: lyrical
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }

